name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & push Docker image 
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: node-app
          tags: latest
          enableBuildKit: false
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
